<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-VKAG1RPA" failures="2" tests="18" name="Category" time="132.495" errors="0" timestamp="2021-02-05T11:20:50 IST">
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_Category" name="selectALL_forCategoryCode" time="6.505"/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_Category" name="createCategoryCode" time="7.087"/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_Category" name="createCategoryCode" time="10.078"/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_Category" name="createCategoryCode" time="3.644"/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_Category" name="createCategoryCode" time="5.394"/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_Category" name="createCategoryCode" time="4.628"/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_Category" name="saveCategoryCode" time="26.276">
    <failure type="java.lang.AssertionError" message="No Error Message validation for save action expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: No Error Message validation for save action expected [true] but found [false]
at com.extraPOSTest.testCases.inventory.maintenance.TC_Category.saveCategoryCode(TC_Category.java:347)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- saveCategoryCode -->
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_Category" name="addTwoSameCategoryCode" time="1.656"/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_Category" name="addTwoSameCategoryCode" time="0.677"/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_Category" name="saveTwoCategoryCode" time="5.398"/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_Category" name="searchCategoryPage" time="3.493"/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_Category" name="searchCategoryPage" time="3.414"/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_Category" name="searchCategoryPage" time="3.344"/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_Category" name="searchCategoryPage" time="4.361"/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_Category" name="checkReverseOrderValidation_CategoryCode" time="1.897"/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_Category" name="checkReverseOrderValidation_CategoryCode" time="0.582"/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_Category" name="checkReverseOrderValidation_CategoryCode" time="0.238"/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_Category" name="checkReverseOrderValidation_CategoryCode" time="21.667">
    <failure type="java.lang.AssertionError" message="No validation for duplicate catcode expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: No validation for duplicate catcode expected [true] but found [false]
at com.extraPOSTest.testCases.inventory.maintenance.TC_Category.checkReverseOrderValidation_CategoryCode(TC_Category.java:897)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- checkReverseOrderValidation_CategoryCode -->
</testsuite> <!-- Category -->
