<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-VKAG1RPA" failures="2" tests="18" name="com.extraPOSTest.testCases.inventory.maintenance.TC_SubCategory" time="95.823" errors="0" timestamp="2021-02-05T11:30:33 IST" skipped="0">
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_SubCategory" name="selectALL_forSubCategoryCode" time="3.957"/>
  <system-out/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_SubCategory" name="createSubCategoryCode" time="2.063"/>
  <system-out/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_SubCategory" name="createSubCategoryCode" time="2.996"/>
  <system-out/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_SubCategory" name="createSubCategoryCode" time="5.090"/>
  <system-out/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_SubCategory" name="createSubCategoryCode" time="3.799"/>
  <system-out/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_SubCategory" name="createSubCategoryCode" time="1.683"/>
  <system-out/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_SubCategory" name="saveSubCategoryCode" time="25.206">
    <failure message="No Error Message validation for save action expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No Error Message validation for save action expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.extraPOSTest.testCases.inventory.maintenance.TC_SubCategory.saveSubCategoryCode(TC_SubCategory.java:340)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- saveSubCategoryCode -->
  <system-out/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_SubCategory" name="addTwoSameSubCategoryCode" time="0.714"/>
  <system-out/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_SubCategory" name="addTwoSameSubCategoryCode" time="1.859"/>
  <system-out/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_SubCategory" name="saveTwoSubCategoryCode" time="5.305"/>
  <system-out/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_SubCategory" name="searchCategoryPage" time="4.414"/>
  <system-out/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_SubCategory" name="searchCategoryPage" time="5.119"/>
  <system-out/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_SubCategory" name="searchCategoryPage" time="4.429"/>
  <system-out/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_SubCategory" name="searchCategoryPage" time="4.580"/>
  <system-out/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_SubCategory" name="checkReverseOrderValidation_SubCategoryCode" time="0.279"/>
  <system-out/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_SubCategory" name="checkReverseOrderValidation_SubCategoryCode" time="21.472">
    <failure message="No validation for duplicate Subcatcode expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No validation for duplicate Subcatcode expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.extraPOSTest.testCases.inventory.maintenance.TC_SubCategory.checkReverseOrderValidation_SubCategoryCode(TC_SubCategory.java:893)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkReverseOrderValidation_SubCategoryCode -->
  <system-out/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_SubCategory" name="checkReverseOrderValidation_SubCategoryCode" time="2.296"/>
  <system-out/>
  <testcase classname="com.extraPOSTest.testCases.inventory.maintenance.TC_SubCategory" name="checkReverseOrderValidation_SubCategoryCode" time="0.562"/>
  <system-out/>
</testsuite> <!-- com.extraPOSTest.testCases.inventory.maintenance.TC_SubCategory -->
